[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma db push --accept-data-loss", "npm run build"]

[start]
cmd = "node dist/index.js"
